# Generated by Django 5.2.14 on 2026-05-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Назва валюти')),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс купівлі')),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс продажу')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюти',
                'ordering': ['-date', 'name'],
            },
        ),
    ]
